name = "VPP Origins"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc28c32b4bca08e0d7ac20ca64537c87f582a8931c1d92911444c7cd39af978d"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.78"
