name = "CMB"
author = "CyberCat5555"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c68f4417661f6c887d11fb3f1fd2fa5984ee20a24474dd3a23af02278ec2917"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.25"

[options]
acceptable-game-versions = ["1.19"]
