name = "Building"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "686b7918b4052457ef3dfaa969f65440a5f09c4fd1109b1a2df430473c049b72"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
