name = "Building"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3510473344b985a0daa4349b008b7b1682e103913ed9ef362f8cdea9f511b703"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
