name = "Building"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e1f4ecf9bc637263509e06986378d52d6a06f0b1aa4de5378cb4a76962884e5"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
