name = "Building"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0faac2338f99b93fb2ac5883ab9214dcdd4af350c6ba3e2946299d23074eec8"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
