name = "Building"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0c18ee7cc544f7feb8a5391f1f3506743ddcdcadec9c3178e80c1e89c2adf58"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
