name = "Building"
author = "Ecorous"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40d8481ff055ff0b77d3b01cc104ee22ec5be62c8611b3c25752f142c9fc65ea"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
