name = "SPRP Modded"
author = "TirFarThoinn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee5a694de5bcb411fa1c797d7f667850fad428f69beed9d8868548fdbdaaf116"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
